### ISSUE TITLE
Deployment to IBM Cloud Container Service

### ISSUE THREAD

**Issue by gmosx** [svanimpe/swift-blog#1]
It would be great if you could explain how to deploy this small app using IBM Cloud Container Service instead of CloudFoundry. Especially how to setup public domain names.

**Comment by svanimpe** [comment]
I'm afraid I don't have much experience with containers. Perhaps these instructions are what you're looking for?

https://developer.ibm.com/swift/2016/03/04/running-kitura-in-an-ibm-container/
https://developer.ibm.com/swift/2016/02/22/10-steps-to-running-a-swift-app-in-an-ibm-container/
