### ISSUE TITLE
Build on Heroku

### ISSUE THREAD

**Issue by nonfungibletunji** [svanimpe/swift-blog#2]
Provide instructions to buld on heroku

**Comment by svanimpe** [comment]
I don't think you can run this project as-is on Heroku as I use IBM's `ConfigurationManager` type to load Bluemix environment variables and set the port.

If you want to use Heroku, I suggest taking a look at https://github.com/kylef/heroku-buildpack-swift and changing the code that sets the port to something that is suitable for Heroku.
